### ISSUE TITLE
出现了openai.error.InvalidRequestError: Invalid URL (POST /v1/chat/completions/chat/completions)

### ISSUE THREAD

**Issue by jinyilun718** [LinLin00000000/vercel-proxy-openai#2]
您好，我在按您的教程配置完成后仍然出现了如下问题，想咨询一下解决方案：
openai.error.InvalidRequestError: Invalid URL (POST/v1/chat/completions/chat/completions)

代码如下：
import openai

openai.api_key = "****"
host = '*****'
url = f'https://{host}/v1/chat/completions'
openai.api_base  = url
messages = [
    {"role": "system", "content": "You are a news creator"},
    {"role": "user",
     "content": f"Write a news article with the title 你好 that spans 3-4 paragraphs and comprehensively covers pertinent and vital information on the topic. Your piece should be both informative and engaging, capturing readers' attention and keeping them informed throughout."},
]

# 调用 GPT-3.5-turbo API

completion = openai.ChatCompletion.create(
    model="gpt-3.5-turbo",
    messages=messages
)
# 获取生成的新闻稿内容
print(completion.choices[0].message["content"]

**Comment by LinLin00000000** [comment]
看起来是 URL 重复了，openai.api_base = url 改为 openai.api_base = host 试试

**Comment by jinyilun718** [comment]
感谢，host/v1后能够正确调用api了
