### ISSUE TITLE
请问404是什么怎么回事

### ISSUE THREAD

**Issue by hh1336** [LinLin00000000/vercel-proxy-openai#6]
![image](https://user-images.githubusercontent.com/36670410/235053629-65ec0307-dff6-4b34-a696-829f7f5a1b99.png)
![image](https://user-images.githubusercontent.com/36670410/235053651-ee987402-32c9-493a-9b50-fdfa7c1d0fce.png)
使用python接口访问也是404

**Comment by LinLin00000000** [comment]
请直接访问聊天端点，可参考 https://github.com/LinLin00000000/vercel-proxy-openai/issues/3#issuecomment-1512342952

**Comment by hh1336** [comment]
> 

好的，感谢
