### ISSUE TITLE
一直遇到超时的问题

### ISSUE THREAD

**Issue by ihorizons2022** [LinLin00000000/vercel-proxy-openai#8]
Retrying langchain.chat_models.openai.ChatOpenAI.completion_with_retry.<locals>._completion_with_retry in 1.0 seconds as it raised APIError: Invalid response object from API: 'An error occurred with this application.\n\nROUTER_EXTERNAL_TARGET_ERROR\n' (HTTP response code was 502).

请问这个和通过vercel转发有关系么

**Comment by LinLin00000000** [comment]
这个咱也不清楚🤔
有可能是你的 host/url 填错了，可以参考 #2

**Comment by ihorizons2022** [comment]
哈喽，不是URL错误，我测试了以下：
1. 如果通过vercel转发就会发生ROUTER_EXTERNAL_TARGET_ERROR，特别是提交的payload比较多的时候，payload少的时候是可以的
2. 直接通过openai的endpoint调用不会出现问题

请问vercel转发有大小的限制么？

**Comment by LinLin00000000** [comment]
应该不是大小限制的问题，我用 node 调用 API 一两千字可以写出来的

> completion_with_retry in 1.0 seconds as it raised APIError

看起来应该是超时相关的问题，估计跟你的项目设置有关🥺

**Comment by ihorizons2022** [comment]
感觉没啥关系，因为代码完全不变动的情况下，仅修改endipoint，就会出现这种情况

**Comment by LinLin00000000** [comment]
那可能你的项目用不了这个方法惹

**Comment by ihorizons2022** [comment]
感谢作者回复。
我在网上看到这么一个贴
https://blog.meathill.com/ai/notes-on-using-vercel-edge-function-to-access-openai-api.html/amp

叙述了如下“由于算法原因，OpenAI API 返回数据的总时间可能比较长，而 Edge Function 的等待时间又限制得很严。所以如果等待 OpenAI 返回全部数据再渲染，可能因为等太久，在 Edge Function 这里会超时。”

请问和我提的问题有相关性么

郭轩
15802161396
[image]
三尺剑网络科技（上海）有限公司

**Comment by LinLin00000000** [comment]
> 感谢作者回复。 我在网上看到这么一个贴 https://blog.meathill.com/ai/notes-on-using-vercel-edge-function-to-access-openai-api.html/amp 叙述了如下“由于算法原因，OpenAI API 返回数据的总时间可能比较长，而 Edge Function 的等待时间又限制得很严。所以如果等待 OpenAI 返回全部数据再渲染，可能因为等太久，在 Edge Function 这里会超时。” 请问和我提的问题有相关性么

应该有点关系，我这个方法的原理差不多就是这样。我自己也是用流式传输的

**Comment by ihorizons2022** [comment]
感谢
close the issue

郭轩
15802161396
[image]
三尺剑网络科技（上海）有限公司
